### PR TITLE
Symfony basics

### PR DESCRIPTION
**Pull request by ngdo-pro**
- AppBundle recreated with yml format and 3-lvl templating
- DoctrineMigrationsBundle installed
- Translator activated with french as default locale
- FOSUserBundle installed
- UserBundle created to inherit from FOSUserBundle (since we will overwrite FOSUserBundle controllers, we need our bundle to be a child of FOSUserBundle, and i think AppBundle should not be a child of a vendor bundle)
- EasyAdminBundle installed
- DoctrineFixturesBundle installed

I don't know if we really need an other bundle to use as "base" in our project.

### CODE REVIEW

**Comment by Kaji-U** [comment]
I think it's good. Ok for me

**Review by shog189 — APPROVED** [review]
It is all good for me !

**Review by wafaworks — APPROVED** [review]
Everything ok! good job :)

**Review by dbeauseigneur — APPROVED** [review]
it's ok for me.

**Review by 2binfree — APPROVED** [review]
ok

**Pull request merged**
