### PR TITLE
Fix database relationships

### PR DESCRIPTION
**Pull request by ngdo-pro**
Hi guys, 
New database schema in order to fit our project : 

+ Payment is now related to BaptismHasUser with a oneToOne relationship (it previously was a manyToOne with Baptism)
+ Baptism is now related to Restaurant with a manyToOne relationship (it was a missing relationship)

Fixtures have been updated to fit the new database schema.

+ User Fixture now works fine (password is fixed, you can now connect with : 
    + name : jean-michel@email.com 
    + password : test

+Baptism's status field is now string instead of boolean, to be able to have at least 3 different status

Wiki is ready to be updated as soon as PR is validated :)

### CODE REVIEW

**Review by 2binfree — APPROVED** [review]
ok

**Review by shog189 — APPROVED** [review]
All good for me ! :+1:

**Review by wafaworks — APPROVED** [review]
Nice work ! 👍

**Review by dbeauseigneur — APPROVED** [review]
OK

**Review by Kaji-U — APPROVED** [review]
It's ok !

**Pull request merged**
