### PR TITLE
database conception 

### PR DESCRIPTION
**Pull request by ngdo-pro**
Here are the wiki links to validate : 

+ [Database](https://github.com/ngdo-pro/food_and_you/wiki/Database)
+ [Tables Relationships](https://github.com/ngdo-pro/food_and_you/wiki/Tables-relationships)
+ [Fields Composition](https://github.com/ngdo-pro/food_and_you/wiki/Fields-composition)

The sidenav will be updated as soon as the database is validated !

### CODE REVIEW

**Review by Kaji-U — APPROVED** [review]
It's ok for me, good work !

**Review by wafaworks — APPROVED** [review]
Excellent work ! 👍

**Review by 2binfree — APPROVED** [review]
ok

**Comment by dbeauseigneur** [comment]
Ok

**Review by shog189 — APPROVED** [review]
I approve this pull request :+1:

**Pull request merged**
